# Question 1

In [6]:
#importing numpy with alias name np
import numpy as np

In [12]:
#creating an array with step 3 
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [16]:
list1,list2=[],[]

#colleccting elements into arrays
for i in range(5):
    x=int(input("Enter elements for list1:"))
    list1.append(x)
for i in range(5):
    x=int(input("Enter elements for list2:"))
    list2.append(x)

#converting llist into arrays
arr1=np.array(list1)
arr2=np.array(list2)

#array concatenation
arr=np.concatenate((arr1,arr2))
print("Array after concatenation:",arr)

#array sorting
sortedarr=np.sort(arr)
print("Sorted array:",sortedarr)

Enter elements for list1:1
Enter elements for list1:2
Enter elements for list1:9
Enter elements for list1:8
Enter elements for list1:6
Enter elements for list2:7
Enter elements for list2:5
Enter elements for list2:11
Enter elements for list2:12
Enter elements for list2:56
Array after concatenation: [ 1  2  9  8  6  7  5 11 12 56]
Sorted array: [ 1  2  5  6  7  8  9 11 12 56]


# Question 3

In [21]:
arr = np.array([[1,2,3,9],[1,2,4,8]])
print(arr,"\nDimensions of the array : ",arr.ndim)
arr1 = np.array([[1,2,3,9],[1,2,4,8],[3,5,8,9]])
print(arr1,"\nDimensions of the array : ",arr1.ndim)

[[1 2 3 9]
 [1 2 4 8]] 
Dimensions of the array :  2
[[1 2 3 9]
 [1 2 4 8]
 [3 5 8 9]] 
Dimensions of the array :  2


# Question 4

In [30]:
arr = np.arange(1,8)
print(arr,"\nShape of Array :",arr.shape)

add_row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",add_row_arr.shape)

# converting using newaxis in column wise
add_col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",add_col_arr.shape)

[1 2 3 4 5 6 7] 
Shape of Array : (7,)

Shape of 2d Array in row major : (1, 7)

Shape of 2d Array in column major : (7, 1)


# Or

In [44]:
x=np.array([1,2,3])
print("array:\n",x)
#shape
print(x.shape)

y=np.expand_dims(x,axis=0)
print("\narray:\n",y)
y.shape

array:
 [1 2 3]
(3,)

array:
 [[1 2 3]]


(1, 3)

# Question 5

In [50]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
print("Horizontal append:\n",np.hstack((arr1,arr2)))
print("Horizontal append:\n",np.vstack((arr1,arr2)))

Horizontal append:
 [1 2 3 5 6 7]
Horizontal append:
 [[1 2 3]
 [5 6 7]]


# Question 6

In [49]:
#Creating an array 
arr_1 = np.array([55,86,55, 16, 25, 11,8, 25, 86, 2, 7, 6, 5, 7, 8, 11])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[[ 2  1]
 [ 5  1]
 [ 6  1]
 [ 7  2]
 [ 8  2]
 [11  2]
 [16  1]
 [25  2]
 [55  2]
 [86  2]]
